/**
 * Three suggested next questions (execution plan §7).
 *
 * Built from what the answer itself reported — the parts it could not answer,
 * and the sectors it did route to — rather than generated by a model. That is
 * deliberate: a suggestion produced by an LLM can propose a question the system
 * cannot answer, which is a worse experience than no suggestion, and it would
 * add a call per turn to a path that is already over its latency budget.
 */

const MAX_CHIPS = 3;

function suggestions(answer: {
  unanswered: string[];
  sectors: string[];
  route: string[];
}): string[] {
  const out: string[] = [];

  // What the system said it could not do is the most honest next question:
  // the reader already knows it is a gap, and narrowing often closes it.
  for (const gap of answer.unanswered) {
    const trimmed = gap.replace(/\s+/g, " ").trim();
    if (trimmed) out.push(`Can you say more about: ${trimmed}`);
    if (out.length >= MAX_CHIPS) return out.slice(0, MAX_CHIPS);
  }

  if (answer.route.includes("forecast")) out.push("How confident is that forecast, and why?");
  if (answer.sectors.length === 1) {
    out.push(`How does that compare with Sri Lanka's other export sectors?`);
  }
  out.push("Which sources support that?");

  return out.slice(0, MAX_CHIPS);
}

export default function FollowUpChips({
  answer,
  onPick,
}: {
  answer: { unanswered: string[]; sectors: string[]; route: string[] };
  onPick: (question: string) => void;
}) {
  const chips = suggestions(answer);
  if (chips.length === 0) return null;

  return (
    <nav aria-label="Suggested follow-up questions" className="print:hidden">
      <ul className="flex flex-wrap gap-2">
        {chips.map((chip) => (
          <li key={chip}>
            <button
              type="button"
              onClick={() => onPick(chip)}
              className="rounded-full bg-white ring-1 ring-inset ring-gray-300 px-3 py-1
                         text-xs text-gray-700 hover:bg-gray-50 focus-visible:outline-2
                         focus-visible:outline-offset-2 focus-visible:outline-teal-600"
            >
              {chip}
            </button>
          </li>
        ))}
      </ul>
    </nav>
  );
}
